
baseurl: "https://aaltoml.github.io/apml"
color-scheme: "#334279" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache

title: "Seminar on Advances in Probabilistic Machine Learning"
description: "Aalto University and ELLIS unit Helsinki Seminar on Advances in Probabilistic Machine Learning"

information: This seminar series aims to provide a platform for young researchers (PhD student or post-doc level) to give invited talks about their research, intending to have a diverse set of talks & speakers on topics related to probabilistic machine learning. 

registration: "https://forms.gle/6fpcokHAwArPEraS6"

details: The presentations are virtual talks (~30 min + 15 min Q&A) given **live over Zoom**. To stimulate discussion and allow for the presentation of ongoing work, the talks will not be recorded unless the speaker separately requests for it. The schedule is in Eastern European Standard Time, click [here](https://greenwichmeantime.com/time/to/eet-local/) for a conversion. 

organizers: "[Martin Trapp](https://trappmartin.github.io) and [Arno Solin](http://arno.solin.fi)"


